Models/Etape.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyQuest.Models
{
    public class Etape
    {
        public Etape()
        {
            Chapitres = new HashSet<Chapitre>();
        }

        [Key]
        public int ID { get; set; }
        public String Titre { get; set; }
        public int Numero { get; set; }
        [ForeignKey("Parcours")]
        public int ParcoursID { get; set; }
        public Parcours Parcours { get; set; }
        public ICollection<Chapitre> Chapitres { get; set; }

    }
}

Pages/Intervenant/Chapitres/Ajouter.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyQuest.Models;

namespace MyQuest.Pages.Intervenant.Chapitres
{
    public class AjouterModel : PageModel
    {
        private readonly MyQuestContext _context;

        public AjouterModel(MyQuestContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Contenu Contenu { get; set; }
        //public IFormFile Fichier { get; set; }

        public IActionResult OnGet(int? chapitreID)
        {
            if (chapitreID == null)
            {
                return NotFound();
            }

            Contenu = new Contenu();
            Contenu.ChapitreID = chapitreID.Value;

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int chapitreID)
        {
            // if(string.IsNullOrEmpty(Contenu.Url)) {
            //     var file = Path.Combine(_environment.ContentRootPath, "./wwwroot", File.FileName);
            //     using (var fileStream = new FileStream(file, FileMode.Create))
            //     {
            //         await File.CopyToAsync(fileStream);
            //     }
            //     Contenu.Url = "\\" + File.FileName;
            // }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            var chapitre = await _context.Chapitre.FindAsync(chapitreID);
            chapitre.Contenus.Add(Contenu);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index", new { chapitreID = chapitreID });
        }
    }
}

Pages/Intervenant/Chapitres/Creer.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyQuest.Models;

namespace MyQuest.Pages.Intervenant.Chapitres
{
    public class CreerModel : PageModel
    {
        private readonly MyQuestContext _context;

        public CreerModel(MyQuestContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Chapitre Chapitre { get; set; }

        public async Task<IActionResult> OnGetAsync(int? coursID)
        {
            if (coursID == null)
            {
                return NotFound();
            }

            var cours = await _context.Cours.FindAsync(coursID);

            if (cours == null)
            {
                return NotFound();
            }

            Chapitre = new Chapitre();
            Chapitre.CoursID = cours.ID;
            Chapitre.Numero =   _context.Entry(cours)
                                .Collection(c => c.Chapitres)
                                .Query()
                                .Count()+1;

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int coursID)
        {
            var cours = await _context.Cours.FindAsync(coursID);

            if (cours == null)
            {
                return NotFound();
            }

            var emptyChapitre = new Chapitre();

            if(await TryUpdateModelAsync<Chapitre>(
                emptyChapitre,
                "chapitre",
                ch => ch.Titre, ch => ch.Libelle, ch => ch.Numero
            ))
            {
                var individu = new Individu(User);
                emptyChapitre.AuteurID = individu.ID;
                cours.Chapitres.Add(emptyChapitre);

                await _context.SaveChangesAsync();

                return RedirectToPage("../Cour/Index",
                                new {coursID = cours.ID});

            }

            return Page();

        }
    }
}

Pages/Intervenant/Chapitres/Modifier.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyQuest.Models;

namespace MyQuest.Pages.Intervenant.Chapitres
{
    public class ModifierModel : PageModel
    {
        private readonly MyQuestContext _context;

        public ModifierModel(MyQuestContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Chapitre Chapitre { get; set; }
        public async Task<IActionResult> OnGetAsync(int? chapitreID)
        {
            if (chapitreID == null)
            {
                return NotFound();
            }

            Chapitre = await _context.Chapitre
                .Include("Cours")
                .FirstOrDefaultAsync(m => m.ID == chapitreID);

            if (Chapitre == null)
            {
                return NotFound();
            }
            return Page();
        }
        public async Task<IActionResult> OnPostAsync(int chapitreID)
        {
            var chapitreToUpdate = await _context.Chapitre
                .Include("Cours")
                .FirstOrDefaultAsync(m => m.ID == chapitreID);

            if (chapitreToUpdate == null)
            {
                return NotFound();
            }

            if(await TryUpdateModelAsync<Chapitre>(
                chapitreToUpdate,
                "chapitre",
                ch => ch.Titre, ch => ch.Numero))
            {
                await _context.SaveChangesAsync();
                return RedirectToPage("../Cour/Index",
                                new { coursID = chapitreToUpdate.Cours.ID });
            }

            return Page();
        }
    }
}

Pages/Intervenant/Chapitres/Supprimer.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MyQuest.Models;

namespace MyQuest.Pages.Intervenant.Chapitres
{
    public class SupprimerModel : PageModel
    {
        private readonly MyQuestContext _context;
        private readonly ILogger<SupprimerModel> _logger;

        public SupprimerModel(MyQuestContext context, ILogger<SupprimerModel> logger)
        {
            _context = context;
            _logger = logger;

        }

        [BindProperty]
        public Chapitre Chapitre { get; set; }
        public string ErrorMessage { get; set; }

        public async Task<IActionResult> OnGetAsync(int? chapitreID, bool? saveChangesError = false)
        {
            if (chapitreID == null)
            {
                return NotFound();
            }

            Chapitre = await _context.Chapitre
                .Include("Contenus")
                .FirstOrDefaultAsync(ch => ch.ID == chapitreID);

            if (Chapitre == null)
            {
                return NotFound();
            }

            if (saveChangesError.GetValueOrDefault())
            {
                ErrorMessage = String.Format("La suppression de {0} à echouée.", chapitreID);
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? chapitreID)
        {
            if (chapitreID == null)
            {
                return NotFound();
            }

            var chapitre = await _context.Chapitre.FindAsync(chapitreID);

            if (Chapitre == null)
            {
                return NotFound();
            }

            try
            {
                _context.Chapitre.Remove(chapitre);
                await _context.SaveChangesAsync();
                return RedirectToPage("../Cour/Index",
                                new {coursID = chapitre.CoursID});
            }
            catch (DbUpdateException ex)
            {
                _logger.LogError(ex, ErrorMessage);
                return RedirectToPage("./Supprimer",
                        new { chapitreID, saveChangesError = true });
            }

            ;
        }
    }
}

Pages/Intervenant/Cour/Ajouter.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyQuest.Models;


namespace MyQuest.Pages.Intervanant.Cour
{
    public class AjouterModel : PageModel

    {
        private readonly MyQuestContext _context;

        public AjouterModel(MyQuestContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Cours Cours { get; set; }

        public async Task<IActionResult> OnGetAsync(int? coursID, string erreur)
        {
            if (coursID == null)
            {
                return NotFound();
            }

            Cours = await _context.Cours
                                .Include(c => c.Apprenants)
                                .Include(c => c.Intervenants)
                                .OrderBy(c => c.ID)
                                .AsSplitQuery()
                                .AsNoTracking()
                                .FirstOrDefaultAsync(m => m.ID == coursID);

            if (coursID == null)
            {
                return NotFound();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int coursID, string emailString, string intervanant)
        {
            var cours = await _context.Cours.FirstOrDefaultAsync(m => m.ID == coursID);

            if (cours==null)
            {
                return NotFound();
            }

            if(!string.IsNullOrEmpty(emailString)){
                string[] emails = emailString.Split(",");

                foreach(var email in emails){

                    var individu = await _context.Individu.FirstOrDefaultAsync(i => i.Email == email);
                    if(!string.IsNullOrEmpty(intervanant))
                    {
                        cours.Intervenants.Add(individu);
                    }
                    else
                    {
                        cours.Apprenants.Add(individu);
                    }
                }
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch(DbUpdateException ex)
                {
                    RedirectToPage("./Ajouter",
                                    new { coursID = coursID, error = ex.ToString() });
                }
            }

            return RedirectToPage("./Ajouter",
                            new {coursID = coursID});
        }

        public async Task<IActionResult> OnPostSupprimer(int coursID, string individuID, string intervenant)
        {
            var cours = await _context.Cours.FindAsync(coursID);

            if(cours == null){
                return NotFound();
            }

            Individu individu;

            if (!string.IsNullOrEmpty(intervenant))
            {
                individu = await _context.Entry(cours)
                                    .Collection(c => c.Intervenants)
                                    .Query()
                                    .FirstOrDefaultAsync(i => i.ID == individuID);

                individu.Intervenir.Remove(cours);
            }
            else
            {
                individu = await _context.Entry(cours)
                                    .Collection(c => c.Apprenants)
                                    .Query()
                                    .FirstOrDefaultAsync(i => i.ID == individuID);

                individu.Apprendre.Remove(cours);
            }

            await _context.SaveChangesAsync();

            return RedirectToPage("./Ajouter",
                            new {coursID = coursID});
        }
    }
}

Pages/Intervenant/Cour/Creer.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyQuest.Models;

namespace MyQuest.Pages.Intervenant.Cour
{
    public class CreerModel : PageModel
    {
        private readonly MyQuestContext _context;

        public CreerModel(MyQuestContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Cours Cours { get; set; }


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var individu = new Individu(User);
            _context.Attach(individu);
            individu.Cours.Add(Cours);
            individu.Intervenir.Add(Cours);
            await _context.SaveChangesAsync();

            return RedirectToPage("../Index");
        }
    }
}

Pages/Intervenant/Cour/Supprimer.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MyQuest.Models;

namespace MyQuest.Pages.Intervenant.Cour
{
    public class SupprimerModel : PageModel
    {
        private readonly MyQuestContext _context;
        private readonly ILogger<SupprimerModel> _logger;

        public SupprimerModel(MyQuestContext context, ILogger<SupprimerModel> logger)
        {
            _context = context;
            _logger = logger;
        }

        [BindProperty]
        public Cours Cours { get; set; }
        public string ErrorMessage { get; set; }

        public async Task<IActionResult> OnGetAsync(int? coursID, bool? saveChangesError = false)
        {
            if (coursID == null)
            {
                return NotFound();
            }

            Cours = await _context.Cours
                            .Include("Chapitres")
                            .AsNoTracking()
                            .FirstOrDefaultAsync(c => c.ID == coursID);

            if (Cours == null)
            {
                return NotFound();
            }

            if (saveChangesError.GetValueOrDefault())
            {
                ErrorMessage = String.Format("La suppression de {0} à echouée.", coursID);
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int coursID)
        {
            var cours = await _context.Cours.FindAsync(coursID);

            if (cours == null)
            {
                return NotFound();
            }

            try
            {
                _context.Cours.Remove(cours);
                await _context.SaveChangesAsync();
                return RedirectToPage("../Index");
            }
            catch (DbUpdateException ex)
            {
                _logger.LogError(ex, ErrorMessage);
                return RedirectToPage("./Supprimer",
                                new { coursID, saveChangesError = true });
            }

        }
    }
}

Pages/Intervenant/Parcour/Etapes/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyQuest.Models;

namespace MyQuest.Pages.Intervenant.Parcour.Etapes
{
    public class IndexModel : PageModel
    {
        private readonly MyQuestContext _context;

        public IndexModel(MyQuestContext context)
        {
            _context = context;
        }
        public IList<Chapitre> Chapitres { get;set; }
        public Etape Etape {get;set;}
        public async Task<IActionResult> OnGetAsync(int? etapeID)
        {
            if (etapeID == null)
            {
                return NotFound();
            }

            Etape = await _context.Etape
                            .Include(e => e.Chapitres)
                            .AsNoTracking()
                            .FirstOrDefaultAsync(i => i.ID == etapeID);

            if(Etape == null)
            {
                return NotFound();
            }

            Chapitres = Etape.Chapitres.OrderBy(ch => ch.CoursID).ToList();

            return Page();
        }

        public async Task<IActionResult> OnPostDelier(int etapeID, int chapitreID)
        {
            var etape = await _context.Etape
                            .Include(e => e.Chapitres)
                            .FirstOrDefaultAsync(e => e.ID == etapeID);

            if (etape == null)
            {
                return NotFound();
            }

            var chapitre = etape.Chapitres.FirstOrDefault(ch => ch.ID == chapitreID);

            etape.Chapitres.Remove(chapitre);

            await _context.SaveChangesAsync();

            return RedirectToPage("./Index",
                            new {etapeID = etapeID});
        }
    }

}

Pages/Intervenant/Parcour/Etapes/Ajouter.cshtml
@page "/Intervenant/Parcours/Etapes/{etapeID}/Ajouter"
@model Myquest.Pages.Intervenant.AjouterChapitresEtapesModel

@{
    ViewData["Title"] = "Ajout Chapitre";
}

<h1 class="text-2xl py-6 text-center">Ajouter un chapitre</h1>
<form class="block max-w-max mx-auto my-4">
    <p>
        Titre: <input type="text" name="search" value=@Model.CurrentFilter />
        <select asp-items="Model.Options" name="coursID"></select>
        <input type="submit" value="Filter"  class="text-sm bg-primary hover:bg-dark-primary text-white py-1 px-2 rounded focus:outline-none focus:shadow-outline"/>
    </p>
</form>
<form method="post">
    <input type="hidden" asp-for=@Model.Etape.ID/>
    <table class="shadow overflow-hidden rounded border-b border-gray-200 max-w-full bg-white mx-auto">
        <thead class="bg-gray-800 text-white">
            <tr>
                <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Id</th>
                <th class="text-left py-3 px-4 uppercase font-semibold text-sm"><a asp-page="./Ajouter" asp-route-etapeID=@Model.Etape.ID asp-route-sortOrder=@Model.TitreSort>
                    Titre @Model.indicateurTri
                </a></th>
                <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Cours</th>
                <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Choisir</th>
            </tr>
        </thead>
        <tbody>
        @{int count = 0;}
        @foreach(var chapitre in Model.Chapitres)
        {
            <tr @if(count % 2 == 1){
                    @("class=bg-gray-100");
                }>
                <td class="text-left py-3 px-4">
                    @Html.DisplayFor(modelItem => chapitre.ID)
                </td>
                <td class="text-left py-3 px-4">
                    @Html.DisplayFor(modelItem => chapitre.Titre)
                </td>
                <td class="text-left py-3 px-4">
                    @Html.DisplayFor(modelItem => chapitre.Cours.Titre)
                </td>
                <td class="text-left py-3 px-4">
                    <input name="SelectedChapitres" type="checkbox" value="@chapitre.ID" />Ajouter<br />
                </td>
            </tr>
            count = count + 1;
        }
            <tr @if(count % 2 == 1){
                    @("class=bg-gray-100");
                }>
                <td colspan="5" class=" py-3 px-4">
                    <button class="text-sm bg-primary hover:bg-dark-primary text-white py-2 px-3 rounded focus:outline-none focus:shadow-outline">Ajouter les chapitres</button>
                </td>
            </tr>
        </tbody>
    </table>

    <p class="py-4 ml-6"><a asp-page="./Index" asp-route-etapeID="@Model.Etape.ID" class="text-primary hover:underline">Retour a la liste des chapitres</a></p>
</form>

Pages/Intervenant/Parcour/Etapes/Creer.cshtml
@page "/Intervenant/Parcours/{parcoursID}/Etapes/Creer"
@model MyQuest.Pages.Intervenant.Parcour.Etapes.CreerModel

@{
    ViewData["Title"] = "Créer Etape";
}

<div class="mx-auto rounded-lg w-max lg:px-20 sm:px-10 px-4 bg-white md:text-base sm:text-sm text-xs mt-8">
    <div class="text-center py-8 ">
        <h1 class="text-3xl font-semibold text-gray-700 dark:text-gray-200">Ajouter une étapes</h1>
    </div>
    <form method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="mb-6">
            <label asp-for="Etape.Numero" class="block mb-2 text-sm text-gray-600 dark:text-gray-400"></label>
            <input asp-for="Etape.Numero" class="w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md focus:outline-none focus:ring focus:ring-indigo-100 focus:border-indigo-300 dark:bg-gray-700 dark:text-white dark:placeholder-gray-500 dark:border-gray-600 dark:focus:ring-gray-900 dark:focus:border-gray-500" />
            <span asp-validation-for="Etape.Numero" class="text-danger"></span>
        </div>
        <div class="mb-6">
            <label asp-for="Etape.Titre" class="block mb-2 text-sm text-gray-600 dark:text-gray-400"></label>
            <input asp-for="Etape.Titre" class="w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md focus:outline-none focus:ring focus:ring-indigo-100 focus:border-indigo-300 dark:bg-gray-700 dark:text-white dark:placeholder-gray-500 dark:border-gray-600 dark:focus:ring-gray-900 dark:focus:border-gray-500" />
            <span asp-validation-for="Etape.Titre" class="text-danger"></span>
        </div>
        <div class="mb-6">
            <input type="submit" value="Creer" class="w-full px-3 py-3 border-2 text-white cursor-pointer bg-primary hover:bg-dark-primary rounded-md focus:bg-primary focus:outline-none" />
        </div>
    </form>
    <p class="pb-6">
        @* ici *@
        <a asp-page="../Index" asp-route-parcoursID="@Model.Etape.ParcoursID" class="text-primary hover:underline">Retour à la liste des étapes</a>
    </p>
</div>

Pages/Intervenant/Parcour/Etapes/Index.cshtml
@page "/Intervenant/Parcours/Etapes/{etapeID?}/{handler?}"
@model MyQuest.Pages.Intervenant.Parcour.Etapes.IndexModel

@{
    ViewData["Title"] = "Etape";
}


<h1 class="text-2xl py-6 text-center">Chapitres de l'etape : @Model.Etape.Titre</h1>

<table class="shadow overflow-hidden rounded border-b border-gray-200 max-w-full bg-white mx-auto">
    <thead class="bg-gray-800 text-white">
        <tr>
            <th class="text-left py-3 px-4 uppercase font-semibold text-sm">
                Nom
            </th>
            <th class="text-left py-3 px-4 uppercase font-semibold text-sm">
                Action
            </th>
        </tr>
    </thead>
    <tbody>
    @{int count = 0;}
    @foreach (var item in Model.Chapitres) {
        <tr @if(count % 2 == 1){
                    @("class=bg-gray-100");
                }>
            <td class="text-left py-3 px-4">
                @Html.DisplayFor(modelItem => item.Titre)
            </td>
            <td class="text-left py-3 px-4">
                <a asp-page="../../Chapitres/Index" asp-route-chapitreID="@item.ID" asp-route-FromEtape="@Model.Etape.ID" ><button type="button" class="mr-3 mb-2 text-sm bg-primary hover:bg-dark-primary text-white py-2 px-3 rounded focus:outline-none focus:shadow-outline">Afficher</button></a>
                <form method="post" asp-page-handler="Delier" asp-route-etapeID="@Model.Etape.ID" asp-route-chapitreID="@item.ID"><button type="submit" class="text-sm bg-red-500 hover:bg-red-700 text-white py-2 px-3 rounded focus:outline-none focus:shadow-outline">Supprimer</button></form>
            </td>
        </tr>
        count = count + 1;
    }
        <tr @if(count % 2 == 1){
                    @("class=bg-gray-100");
                }>
                <td colspan="5" class=" py-3 px-4">
                    <button class="text-sm bg-primary hover:bg-dark-primary text-white py-2 px-3 rounded focus:outline-none focus:shadow-outline"><a asp-page="./Ajouter" asp-route-etapeID=@Model.Etape.ID>Ajouter un chapitre</a></button>
                </td>
            </tr>
    </tbody>
</table>

<p class="py-4 ml-6"><a asp-page ="../Index" asp-route-parcoursID="@Model.Etape.ParcoursID" class="text-primary hover:underline">Retour à la liste des étapes</a></p>

Pages/Intervenant/Parcour/Etapes/Modifier.cshtml
@page "/Intervenant/Parcours/Etapes/{etapeID}/Modifier"
@model MyQuest.Pages.Intervenant.Parcour.Etapes.ModifierModel

@{
    ViewData["Title"] = "Modifier Etape";
}

<div class="mx-auto rounded-lg w-max lg:px-20 sm:px-10 px-4 bg-white md:text-base sm:text-sm text-xs mt-8">
    <div class="text-center py-8 ">
        <h1 class="text-3xl font-semibold text-gray-700 dark:text-gray-200">Modifier l'étape</h1>
    </div>
    <form method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Etape.ID" />
        <div class="mb-6">
            <label asp-for="Etape.Numero" class="block mb-2 text-sm text-gray-600 dark:text-gray-400"></label>
            <input asp-for="Etape.Numero" class="w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md focus:outline-none focus:ring focus:ring-indigo-100 focus:border-indigo-300 dark:bg-gray-700 dark:text-white dark:placeholder-gray-500 dark:border-gray-600 dark:focus:ring-gray-900 dark:focus:border-gray-500" />
            <span asp-validation-for="Etape.Numero" class="text-danger"></span>
        </div>
        <div class="mb-6">
            <label asp-for="Etape.Titre" class="block mb-2 text-sm text-gray-600 dark:text-gray-400"></label>
            <input asp-for="Etape.Titre" class="w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md focus:outline-none focus:ring focus:ring-indigo-100 focus:border-indigo-300 dark:bg-gray-700 dark:text-white dark:placeholder-gray-500 dark:border-gray-600 dark:focus:ring-gray-900 dark:focus:border-gray-500" />
            <span asp-validation-for="Etape.Titre" class="text-danger"></span>
        </div>
        <div class="mb-6">
            <input type="submit" value="Modifier" class="w-full px-3 py-3 border-2 text-white cursor-pointer bg-primary hover:bg-dark-primary rounded-md focus:bg-primary focus:outline-none" />
        </div>
    </form>
    <p class="pb-6">
        <a asp-page="../Index" asp-route-parcoursID=@Model.Etape.ParcoursID class="text-primary hover:underline">Retour à la liste des étapes</a>
    </p>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Intervenant/Parcour/Etapes/Supprimer.cshtml
@page "/Intervenant/Parcours/Etapes/{etapeID}/Supprimer"
@model MyQuest.Pages.Intervenant.Parcour.Etapes.SupprimerModel

@{
    ViewData["Title"] = "Delete";
}

<div class="mx-auto rounded-lg w-max lg:px-20 sm:px-10 px-4 bg-white md:text-base sm:text-sm text-xs mt-8">
    <div class="text-center py-8 ">
        <h1 class="text-3xl font-semibold text-gray-700 dark:text-gray-200">Êtes-vous sûr de supprimer cette étape ?</h1>
    </div>
    <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4 border-b border-gray-400">
        <p class="text-gray-600">
            @Html.DisplayNameFor(model => model.Etape.Titre)
        </p>
        <p>
            @Html.DisplayFor(model => model.Etape.Titre)
        </p>
    </div>
    <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4">
        <p class="text-gray-600">
            @Html.DisplayNameFor(model => model.Etape.Numero)
        </p>
        <p>
            @Html.DisplayFor(model =>  model.Etape.Numero)
        </p>
    </div>

    <form method="post">
        <input type="submit" value="Supprimer" class="w-full px-3 py-3 border-2 text-white cursor-pointer bg-red-700 hover:bg-red-900 rounded-md focus:bg-red-700 focus:outline-none"/><br><br>
    </form>
    <p class="pb-6">
        <a asp-page="../Index" asp-route-parcoursID="@Model.Etape.ParcoursID" class="text-primary hover:underline">Retour à la liste des étapes</a>
    </p>
</div>