Pages/Apprenant/Quizz/Passer.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyQuest.Models;

namespace MyQuest.Pages.Apprenant
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class PasserModel : PageModel
    {
        private readonly MyQuestContext _context;

        public PasserModel(MyQuestContext context)
        {
            _context = context;
        }

        public Quiz Quiz { get; set; }

        [BindProperty]
        public List<Question> Questions { get; set; }
        public Evaluation Evaluation { get; set; }
        public float? CurrentScore { get; set; }

        public async Task<IActionResult> OnGetAsync(int? quizID)
        {
            if (quizID == null)
            {
                return NotFound();
            }

            Quiz = await _context.Quiz.FindAsync(quizID);

            if(Quiz == null)
            {
                return NotFound();
            }

            var individu = new Individu(User);

            Evaluation = await _context.Entry(Quiz)
                        .Collection(q => q.Evaluations)
                        .Query()
                        .FirstOrDefaultAsync(e => e.IndividuID == individu.ID);

            if (Evaluation == null)
            {
                Evaluation = new Evaluation(User, Quiz);
                _context.Evaluation.Add(Evaluation);
                await _context.SaveChangesAsync();
            }

            var questions = await _context.Entry(Quiz)
                        .Collection(q => q.Questions)
                        .Query()
                        .Where(qu => qu.Active)
                        .Include(qu => qu.Reponses)
                        .AsNoTracking()
                        .ToListAsync();

            Questions = questions
                        .OrderBy(qu => Guid.NewGuid())
                        .Take(Quiz.Max_Question)
                        .ToList();

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int quizID)
        {
            Quiz = await _context.Quiz.FindAsync(quizID);

            if(Quiz == null)
            {
                return NotFound();
            }

            var data = new List<Question>();
            var individu = new Individu(User);

            CurrentScore = 0;

            Evaluation = await _context.Entry(Quiz)
                        .Collection(q => q.Evaluations)
                        .Query()
                        .FirstOrDefaultAsync(e => e.IndividuID == individu.ID);

            foreach (var question in Questions)
            {
                float scoreQuestion = 0;
                var questionOrigin = await _context.Question
                                            .Include(qu => qu.Reponses)
                                            .AsNoTracking()
                                            .FirstOrDefaultAsync(qu => qu.ID == question.ID);

                foreach (var reponse in question.Reponses)
                {
                    var reponseOrigin = questionOrigin.Reponses.FirstOrDefault(r => r.ID == reponse.ID);

                    if(!reponse.Choisi) { continue; }

                    if(reponseOrigin.Valide) { scoreQuestion += reponseOrigin.Valeur; }
                    else
                    {
                        scoreQuestion -= reponseOrigin.Valeur;
                        questionOrigin.Erreur = true;
                    }

                }

                if(questionOrigin.Poids < scoreQuestion)
                {
                    CurrentScore += questionOrigin.Poids;
                    continue;
                }
                if(questionOrigin.Max_Penalite > scoreQuestion)
                {
                    CurrentScore -= questionOrigin.Max_Penalite;
                    continue;
                }

                data.Add(questionOrigin);
                CurrentScore += scoreQuestion;
            }

            Evaluation.UpdateScore(CurrentScore.Value);

            await _context.SaveChangesAsync();

            Questions = data;

            return Page();
        }

    }
}

Pages/Intervenant/Chapitres/Ajouter.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyQuest.Models;

namespace MyQuest.Pages.Intervenant.Chapitres
{
    public class AjouterModel : PageModel
    {
        private readonly MyQuestContext _context;

        public AjouterModel(MyQuestContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Contenu Contenu { get; set; }
        //public IFormFile Fichier { get; set; }

        public IActionResult OnGet(int? chapitreID)
        {
            if (chapitreID == null)
            {
                return NotFound();
            }

            Contenu = new Contenu();
            Contenu.ChapitreID = chapitreID.Value;

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int chapitreID)
        {
            // if(string.IsNullOrEmpty(Contenu.Url)) {
            //     var file = Path.Combine(_environment.ContentRootPath, "./wwwroot", File.FileName);
            //     using (var fileStream = new FileStream(file, FileMode.Create))
            //     {
            //         await File.CopyToAsync(fileStream);
            //     }
            //     Contenu.Url = "\\" + File.FileName;
            // }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            var chapitre = await _context.Chapitre.FindAsync(chapitreID);
            chapitre.Contenus.Add(Contenu);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index", new { chapitreID = chapitreID });
        }
    }
}

Pages/Intervenant/Chapitres/Creer.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyQuest.Models;

namespace MyQuest.Pages.Intervenant.Chapitres
{
    public class CreerModel : PageModel
    {
        private readonly MyQuestContext _context;

        public CreerModel(MyQuestContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Chapitre Chapitre { get; set; }

        public async Task<IActionResult> OnGetAsync(int? coursID)
        {
            if (coursID == null)
            {
                return NotFound();
            }

            var cours = await _context.Cours.FindAsync(coursID);

            if (cours == null)
            {
                return NotFound();
            }

            Chapitre = new Chapitre();
            Chapitre.CoursID = cours.ID;
            Chapitre.Numero =   _context.Entry(cours)
                                .Collection(c => c.Chapitres)
                                .Query()
                                .Count()+1;

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int coursID)
        {
            var cours = await _context.Cours.FindAsync(coursID);

            if (cours == null)
            {
                return NotFound();
            }

            var emptyChapitre = new Chapitre();

            if(await TryUpdateModelAsync<Chapitre>(
                emptyChapitre,
                "chapitre",
                ch => ch.Titre, ch => ch.Libelle, ch => ch.Numero
            ))
            {
                var individu = new Individu(User);
                emptyChapitre.AuteurID = individu.ID;
                cours.Chapitres.Add(emptyChapitre);

                await _context.SaveChangesAsync();

                return RedirectToPage("../Cour/Index",
                                new {coursID = cours.ID});

            }

            return Page();

        }
    }
}

Pages/Intervenant/Chapitres/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyQuest.Models;

namespace MyQuest.Pages.Intervenant.Chapitres
{
    public class IndexModel : PageModel
    {
        private readonly MyQuestContext _context;

        public IndexModel(MyQuestContext context)
        {
            _context = context;
        }

        public Chapitre Chapitre { get; set; }
        public IList<Contenu> Contenu { get; set; }

        [BindProperty(SupportsGet=true)]
        public int? FromEtape { get; set; }

        public async Task<IActionResult> OnGetAsync(int? chapitreID)
        {
            if (chapitreID == null)
            {
                return NotFound();
            }

            Chapitre = await _context.Chapitre
                .Include(ch => ch.Contenus)
                .Include(ch => ch.Quiz)
                .ThenInclude(q => q.Questions)
                .AsSplitQuery()
                .OrderBy(ch => ch.ID)
                .AsNoTracking()
                .FirstOrDefaultAsync(ch => ch.ID == chapitreID.Value);

            if (Chapitre == null)
            {
                return NotFound();
            }

            Contenu = Chapitre.Contenus.ToList();

            return Page();
        }

        public async Task<IActionResult> OnPostSupprimer(int contenuID)
        {
            var contenu = await _context.Contenu.FindAsync(contenuID);

            if (contenu == null)
            {
                return NotFound();
            }

            _context.Contenu.Remove(contenu);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Intervenant/Chapitres/Modifier.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyQuest.Models;

namespace MyQuest.Pages.Intervenant.Chapitres
{
    public class ModifierModel : PageModel
    {
        private readonly MyQuestContext _context;

        public ModifierModel(MyQuestContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Chapitre Chapitre { get; set; }
        public async Task<IActionResult> OnGetAsync(int? chapitreID)
        {
            if (chapitreID == null)
            {
                return NotFound();
            }

            Chapitre = await _context.Chapitre
                .Include("Cours")
                .FirstOrDefaultAsync(m => m.ID == chapitreID);

            if (Chapitre == null)
            {
                return NotFound();
            }
            return Page();
        }
        public async Task<IActionResult> OnPostAsync(int chapitreID)
        {
            var chapitreToUpdate = await _context.Chapitre
                .Include("Cours")
                .FirstOrDefaultAsync(m => m.ID == chapitreID);

            if (chapitreToUpdate == null)
            {
                return NotFound();
            }

            if(await TryUpdateModelAsync<Chapitre>(
                chapitreToUpdate,
                "chapitre",
                ch => ch.Titre, ch => ch.Numero))
            {
                await _context.SaveChangesAsync();
                return RedirectToPage("../Cour/Index",
                                new { coursID = chapitreToUpdate.Cours.ID });
            }

            return Page();
        }
    }
}

Pages/Intervenant/Chapitres/Supprimer.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MyQuest.Models;

namespace MyQuest.Pages.Intervenant.Chapitres
{
    public class SupprimerModel : PageModel
    {
        private readonly MyQuestContext _context;
        private readonly ILogger<SupprimerModel> _logger;

        public SupprimerModel(MyQuestContext context, ILogger<SupprimerModel> logger)
        {
            _context = context;
            _logger = logger;

        }

        [BindProperty]
        public Chapitre Chapitre { get; set; }
        public string ErrorMessage { get; set; }

        public async Task<IActionResult> OnGetAsync(int? chapitreID, bool? saveChangesError = false)
        {
            if (chapitreID == null)
            {
                return NotFound();
            }

            Chapitre = await _context.Chapitre
                .Include("Contenus")
                .FirstOrDefaultAsync(ch => ch.ID == chapitreID);

            if (Chapitre == null)
            {
                return NotFound();
            }

            if (saveChangesError.GetValueOrDefault())
            {
                ErrorMessage = String.Format("La suppression de {0} à echouée.", chapitreID);
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? chapitreID)
        {
            if (chapitreID == null)
            {
                return NotFound();
            }

            var chapitre = await _context.Chapitre.FindAsync(chapitreID);

            if (Chapitre == null)
            {
                return NotFound();
            }

            try
            {
                _context.Chapitre.Remove(chapitre);
                await _context.SaveChangesAsync();
                return RedirectToPage("../Cour/Index",
                                new {coursID = chapitre.CoursID});
            }
            catch (DbUpdateException ex)
            {
                _logger.LogError(ex, ErrorMessage);
                return RedirectToPage("./Supprimer",
                        new { chapitreID, saveChangesError = true });
            }

            ;
        }
    }
}

Pages/Intervenant/Cour/Creer.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyQuest.Models;

namespace MyQuest.Pages.Intervenant.Cour
{
    public class CreerModel : PageModel
    {
        private readonly MyQuestContext _context;

        public CreerModel(MyQuestContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Cours Cours { get; set; }


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var individu = new Individu(User);
            _context.Attach(individu);
            individu.Cours.Add(Cours);
            individu.Intervenir.Add(Cours);
            await _context.SaveChangesAsync();

            return RedirectToPage("../Index");
        }
    }
}

Pages/Intervenant/Cour/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyQuest.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MyQuest.Pages.Intervenant.Cour
{
    public class IndexModel : PageModel
    {
        private readonly MyQuestContext _context;

        public IndexModel(MyQuestContext context)
        {
            _context = context;
        }

        public Cours Cours { get; set; }
        public IList<Chapitre> Chapitres { get; set; }

        public async Task<IActionResult> OnGetAsync(int? coursID)
        {
            if (coursID == null)
            {
                return NotFound();
            }

            Cours = await _context.Cours.Include("Chapitres").AsNoTracking().FirstOrDefaultAsync(c => c.ID == coursID.Value);

            if(Cours == null)
            {
                return NotFound();
            }

            Chapitres = Cours.Chapitres.ToList();

            return Page();

        }
    }
}

Pages/Intervenant/Groupes/Creer.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyQuest.Models;

namespace MyQuest.Pages.Intervanant.Groupes
{
    public class CreerModel : PageModel
    {
        private readonly MyQuestContext _context;

        public CreerModel(MyQuestContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Groupe Groupe { get; set; }


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Groupe.Add(Groupe);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Intervenant/Quizz/Creer.cshtml
@page "/Intervenant/Cours/Chapitre/{chapitreID}/Creer"
@model MyQuest.Pages.Intervanant.Quizz.CreerModel

@{
    ViewData["Title"] = "Nouveau Quiz";
}

<div class="mx-auto rounded-lg w-max lg:px-20 sm:px-10 px-4 bg-white md:text-base sm:text-sm text-xs mt-8">
    <div class="text-center py-8 ">
        <h1 class="text-3xl font-semibold text-gray-700 dark:text-gray-200">Ajouter un quiz</h1>
    </div>
    <form method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="mb-6">
            <label asp-for="Quiz.Titre" class="block mb-2 text-sm text-gray-600 dark:text-gray-400"></label>
            <input asp-for="Quiz.Titre" class="w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md focus:outline-none focus:ring focus:ring-indigo-100 focus:border-indigo-300 dark:bg-gray-700 dark:text-white dark:placeholder-gray-500 dark:border-gray-600 dark:focus:ring-gray-900 dark:focus:border-gray-500" />
            <span asp-validation-for="Quiz.Titre" class="text-danger"></span>
        </div>
        <div class="mb-6">
            <label asp-for="Quiz.Max_Question" class="block mb-2 text-sm text-gray-600 dark:text-gray-400"></label>
            <input asp-for="Quiz.Max_Question" class="w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md focus:outline-none focus:ring focus:ring-indigo-100 focus:border-indigo-300 dark:bg-gray-700 dark:text-white dark:placeholder-gray-500 dark:border-gray-600 dark:focus:ring-gray-900 dark:focus:border-gray-500" />
            <span asp-validation-for="Quiz.Max_Question" class="text-danger"></span>
        </div>
        <div class="mb-6">
            <label asp-for="Quiz.Publique" class="block mb-2 text-sm text-gray-600 dark:text-gray-400"></label>
            <input asp-for="Quiz.Publique" class="w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md focus:outline-none focus:ring focus:ring-indigo-100 focus:border-indigo-300 dark:bg-gray-700 dark:text-white dark:placeholder-gray-500 dark:border-gray-600 dark:focus:ring-gray-900 dark:focus:border-gray-500" checked/>
            <span asp-validation-for="Quiz.Publique" class="text-danger"></span>
        <div class="mb-6">
            <input type="submit" value="Créer" class="w-full px-3 py-3 border-2 text-white cursor-pointer bg-primary hover:bg-dark-primary rounded-md focus:bg-primary focus:outline-none" />
        </div>
    </form>
    <p class="pb-6">
        <a asp-page="Index" class="text-primary hover:underline">Retour à la liste des quiz</a>
    </p>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Intervenant/Quizz/Index.cshtml
@page "/Intervenant/Cours/Chapitres/Quiz/{quizID?}"
@model MyQuest.Pages.Intervanant.Quizz.IndexModel

@{
    ViewData["Title"] = "Liste Question";
}

<h1 class="text-2xl py-6 text-center">Vos contenus</h1>
<div class="lg:max-w-none md:max-w-min sm:max-w-screen-sm max-w-min md:px-4 mx-auto">
    <table class="shadow overflow-hidden rounded border-b border-gray-200 max-w-full bg-white mx-auto">
        <thead class="bg-gray-800 text-white">
            <tr>
                <th class="text-left py-3 px-4 uppercase font-semibold text-sm">
                    <label asp-for="Questions[0].Enonce"></label>
                </th>
                <th class="text-left py-3 px-4 uppercase font-semibold text-sm">
                    <label asp-for="Questions[0].Poids"></label>
                </th>
                <th class="text-left py-3 px-4 uppercase font-semibold text-sm">
                    Nombre de réponses
                </th>
                <th class="text-left py-3 px-4 uppercase font-semibold text-sm">
                    <label asp-for="Questions[0].Niveau"></label>
                </th>
                <th class="text-left py-3 px-4 uppercase font-semibold text-sm">
                    <label asp-for="Questions[0].Active"></label>
                </th>
                <th class="text-left py-3 px-4 uppercase font-semibold text-sm">
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
        @{int count = 0;}
        @foreach (var question in Model.Questions) {
            <tr @if(count % 2 == 1){
                        @("class=bg-gray-100");
                    }>
                <td class="text-left py-3 px-4">
                    @Html.DisplayFor(modelItem => question.Enonce)
                </td>
                <td class="text-left py-3 px-4">
                    @Html.DisplayFor(modelItem => question.Poids)
                </td>
                <td class="text-left py-3 px-4">
                    @question.Reponses.Count()
                </td>
                <td class="text-left py-3 px-4">
                    @Html.DisplayFor(modelItem => question.Niveau)
                </td>
                <td class="text-left py-3 px-4">
                    @Html.DisplayFor(modelItem => question.Active)
                </td>
                <td>
                    <a asp-page="./Questions/Modifier" asp-route-questionID=@question.ID>
                        <button type="button" class="text-sm bg-primary hover:bg-dark-primary text-white py-2 px-3 rounded focus:outline-none focus:shadow-outline">Modifier</button>
                    </a>
                    <form method="post" class="inline">
                        <button type="button" asp-page-handler="Supprimer" asp-route-questionID=@question.ID class="text-sm bg-red-500 hover:bg-red-700  text-white py-2 px-3 rounded focus:outline-none focus:shadow-outline">Supprimer</button>
                    </form>
                </td>
            </tr>
            count = count + 1;
        }
            <tr @if(count % 2 == 1){
                    @("class=bg-gray-100");
                }>
                <td colspan="6" class=" py-3 px-4">
                    <a asp-page="./Questions/Creer" asp-route-quizID=@Model.Quiz.ID class="text-primary hover:underline"><button type="button" class="text-sm bg-primary hover:bg-dark-primary text-white py-2 px-3 rounded focus:outline-none focus:shadow-outline">Ajouter question</button></a>
                </td>
            </tr>
        </tbody>
    </table>
</div>
<p class="py-4 ml-6">
    <a asp-page="../Chapitres/Index" asp-route-chapitreID="@Model.Quiz.ChapitreID" class="text-primary hover:underline">Retour au chapitre</a>
</p>

Pages/Intervenant/Quizz/Modifier.cshtml
@page "/Intervenant/Cours/Chapitres/Quiz/{quizID?}/Modifier"
@model MyQuest.Pages.Intervanant.Quizz.ModifierModel

@{
    ViewData["Title"] = "Modification";
}


<div class="mx-auto rounded-lg w-max lg:px-20 sm:px-10 px-4 bg-white md:text-base sm:text-sm text-xs mt-8">
    <div class="text-center py-8 ">
        <h1 class="text-3xl font-semibold text-gray-700 dark:text-gray-200">Editer un quiz</h1>
    </div>
    <form method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="mb-6">
            <label asp-for="Quiz.Titre" class="block mb-2 text-sm text-gray-600 dark:text-gray-400"></label>
            <input asp-for="Quiz.Titre" class="w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md focus:outline-none focus:ring focus:ring-indigo-100 focus:border-indigo-300 dark:bg-gray-700 dark:text-white dark:placeholder-gray-500 dark:border-gray-600 dark:focus:ring-gray-900 dark:focus:border-gray-500" />
            <span asp-validation-for="Quiz.Titre" class="text-danger"></span>
        </div>
        <div class="mb-6">
            <label asp-for="Quiz.Max_Question" class="block mb-2 text-sm text-gray-600 dark:text-gray-400"></label>
            <input asp-for="Quiz.Max_Question" class="w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md focus:outline-none focus:ring focus:ring-indigo-100 focus:border-indigo-300 dark:bg-gray-700 dark:text-white dark:placeholder-gray-500 dark:border-gray-600 dark:focus:ring-gray-900 dark:focus:border-gray-500" />
            <span asp-validation-for="Quiz.Max_Question" class="text-danger"></span>
        </div>
        <div class="mb-6">
            <label asp-for="Quiz.Publique" class="block mb-2 text-sm text-gray-600 dark:text-gray-400"></label>
            <input asp-for="Quiz.Publique" class="w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md focus:outline-none focus:ring focus:ring-indigo-100 focus:border-indigo-300 dark:bg-gray-700 dark:text-white dark:placeholder-gray-500 dark:border-gray-600 dark:focus:ring-gray-900 dark:focus:border-gray-500" />
            <span asp-validation-for="Quiz.Publique" class="text-danger"></span>
        </div>
        <div class="mb-6">
            <input type="submit" value="Sauvegarder" class="w-full px-3 py-3 border-2 text-white cursor-pointer bg-primary hover:bg-dark-primary rounded-md focus:bg-primary focus:outline-none" />
        </div>
    </form>
    <p class="pb-6">
        <a asp-page="../Chapitres/Index" asp-route-chapitreID="@Model.Quiz.ChapitreID" class="text-primary hover:underline">Retour à la liste des chapitres</a>
    </p>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Intervenant/Quizz/Supprimer.cshtml
@page "/Quiz/{quizID}/Supprimer"
@model MyQuest.Pages.Intervanant.Quizz.SupprimerModel;

@{
    ViewData["Title"] = "Suppression";
}

<div class="mx-auto rounded-lg w-max lg:px-20 sm:px-10 px-4 bg-white md:text-base sm:text-sm text-xs mt-8">
    <div class="text-center py-8 ">
        <h1 class="text-3xl font-semibold text-gray-700 dark:text-gray-200">Êtes-vous sûr de supprimer ce quiz ?</h1>
    </div>
    <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4 border-b border-gray-400">
        <p class="text-gray-600">
            @Html.DisplayNameFor(model => model.Quiz.Titre)
        </p>
        <p>
            @Html.DisplayFor(model => model.Quiz.Titre)
        </p>
    </div>
    <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4 border-b border-gray-400">
        <p class="text-gray-600">
            @Html.DisplayNameFor(model => model.Quiz.Langue)
        </p>
        <p>
            @Html.DisplayFor(model => model.Quiz.Langue)
        </p>
    </div>
    <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4">
        <p class="text-gray-600">
            @Html.DisplayNameFor(model => model.Quiz.Publique)
        </p>
        <p>
            @Html.DisplayFor(model => model.Quiz.Publique)
        </p>
    </div>

    <form method="post">
        <input type="hidden" asp-for="Quiz.ID" />
        <input type="submit" value="Supprimer" class="w-full px-3 py-3 border-2 text-white cursor-pointer bg-red-700 hover:bg-red-900 rounded-md focus:bg-red-700 focus:outline-none" /><br><br>
    </form>
    <p class="pb-6">
        <a asp-page="../Chapitres/Index" asp-route-chapitreID="@Model.Quiz.ChapitreID" class="text-primary hover:underline">Retour au chapitre</a>
    </p>
</div>